// سجل مركزي للأيقونات الاحترافية (Lucide) — بديل الإيموجي في كل الموقع.
// أي مكان كان بيخزّن "إيموجي" كقيمة (تصنيف، مجال حياة، وضع الصيانة...)
// بقى يخزّن *مفتاح نصي* بدل الرمز، وده بيرندره عن طريق DynamicIcon.
// كده الشكل موحّد، قابل للتحجيم بالـ CSS، ومتوافق مع أي ثيم (فاتح/غامق).

import {
  Activity,
  AlertTriangle,
  Archive,
  ArrowRight,
  Baby,
  Ban,
  BarChart3,
  Bell,
  BellOff,
  Bike,
  BookOpen,
  Brain,
  Briefcase,
  Building2,
  Calendar,
  CalendarDays,
  CalendarRange,
  Camera,
  Car,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronsDown,
  ChevronsUp,
  Circle,
  ClipboardList,
  Coffee,
  Compass,
  Construction,
  Dumbbell,
  Download,
  Eye,
  EyeOff,
  Feather,
  Flag,
  Flame,
  Flower2,
  Folder,
  FolderOpen,
  Gamepad2,
  Gift,
  Globe2,
  GraduationCap,
  Hand,
  HandHeart,
  Heart,
  Home,
  Hourglass,
  Key,
  Landmark,
  Laptop,
  Leaf,
  ListChecks,
  LogOut,
  Lock,
  Mic2,
  Moon,
  Mountain,
  Music,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Pause,
  Pencil,
  PiggyBank,
  Plane,
  Play,
  Plus,
  Puzzle,
  Redo2,
  Repeat,
  Rocket,
  Save,
  Search,
  Settings,
  Settings2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Shirt,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  StickyNote,
  Sun,
  Sunrise,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingUp,
  Trophy,
  Undo2,
  Users,
  Utensils,
  Volume2,
  VolumeX,
  Wallet,
  Waves,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react';

export const ICON_MAP = {
  activity: Activity,
  alert: AlertTriangle,
  archive: Archive,
  'arrow-right': ArrowRight,
  baby: Baby,
  ban: Ban,
  'bar-chart': BarChart3,
  bell: Bell,
  'bell-off': BellOff,
  bike: Bike,
  'book-open': BookOpen,
  brain: Brain,
  briefcase: Briefcase,
  building: Building2,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'calendar-range': CalendarRange,
  camera: Camera,
  car: Car,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevrons-down': ChevronsDown,
  'chevrons-up': ChevronsUp,
  circle: Circle,
  'clipboard-list': ClipboardList,
  coffee: Coffee,
  compass: Compass,
  construction: Construction,
  dumbbell: Dumbbell,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  feather: Feather,
  flag: Flag,
  flame: Flame,
  flower: Flower2,
  folder: Folder,
  'folder-open': FolderOpen,
  gamepad: Gamepad2,
  gift: Gift,
  globe: Globe2,
  'graduation-cap': GraduationCap,
  hand: Hand,
  'hand-heart': HandHeart,
  heart: Heart,
  home: Home,
  hourglass: Hourglass,
  key: Key,
  landmark: Landmark,
  laptop: Laptop,
  leaf: Leaf,
  'list-checks': ListChecks,
  'log-out': LogOut,
  lock: Lock,
  mic: Mic2,
  moon: Moon,
  mountain: Mountain,
  music: Music,
  paintbrush: Paintbrush,
  palette: Palette,
  'party-popper': PartyPopper,
  'paw-print': PawPrint,
  pause: Pause,
  pencil: Pencil,
  'piggy-bank': PiggyBank,
  plane: Plane,
  play: Play,
  plus: Plus,
  puzzle: Puzzle,
  repeat: Repeat,
  rocket: Rocket,
  save: Save,
  search: Search,
  settings: Settings,
  'settings-2': Settings2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  shirt: Shirt,
  sliders: SlidersHorizontal,
  smile: Smile,
  sparkles: Sparkles,
  sprout: Sprout,
  star: Star,
  stethoscope: Stethoscope,
  'sticky-note': StickyNote,
  sun: Sun,
  sunrise: Sunrise,
  tag: Tag,
  target: Target,
  timer: Timer,
  trash: Trash2,
  'trending-up': TrendingUp,
  trophy: Trophy,
  undo: Undo2,
  redo: Redo2,
  users: Users,
  utensils: Utensils,
  'volume-high': Volume2,
  'volume-off': VolumeX,
  wallet: Wallet,
  waves: Waves,
  wrench: Wrench,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconKey = keyof typeof ICON_MAP;

interface DynamicIconProps {
  name?: string | null;
  size?: number;
  strokeWidth?: number;
  className?: string;
  'aria-hidden'?: boolean;
  fallback?: IconKey;
}

// بيرندر أيقونة Lucide لو الاسم متعرّف في ICON_MAP. لو القيمة مش معروفة (مثلاً
// إيموجي قديم اتخزّن قبل التحديث ده، أو نص حر كتبه المستخدم في مجال حياة)،
// بيرجع النص الخام زي ما هو من غير ما يكسر حاجة — توافقية مع بيانات قديمة.
export function DynamicIcon({ name, size = 18, strokeWidth, className, fallback, ...rest }: DynamicIconProps) {
  const key = (name || fallback) as IconKey | undefined;
  const Icon = key ? ICON_MAP[key] : undefined;
  if (!Icon) {
    return name ? (
      <span className={className} aria-hidden="true">
        {name}
      </span>
    ) : null;
  }
  return (
    <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden={rest['aria-hidden'] !== false} />
  );
}
